[package]
name = "rproxy-core"
version.workspace = true
edition.workspace = true

[dependencies]
rproxy-cert = { path = "../rproxy-cert" }
tokio.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
http.workspace = true
bytes.workspace = true
futures-util.workspace = true
async-trait.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
tokio-rustls.workspace = true
flate2 = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
rcgen.workspace = true
